### ISSUE TITLE
Files created by pvenv are not ignored by git

### ISSUE THREAD

**Issue by bhoeting** [codeforamerica/pdfhook#12]
After successfully setting up the project, the files/folders below are created, but aren't ignored by git.  Which ones should be ignored?

```
bin/
gaffer/
pip-selfcheck.json
pyvenv.cfg
```

**Comment by bengolder** [comment]
all of them. Thanks!
In fact, I should also remove `gaffer` as a requirement. It's wholly unnecessary to the project.

**Comment by bengolder** [comment]
closed with https://github.com/codeforamerica/pdfhook/commit/ab172f902404f8e6adb7842a8b03a05c1c44faad
