### ISSUE TITLE
3/5 Code Across SF Agenda

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/pdfhook#15]
### Pitch: pdfhook

Turning PDF forms into APIs that fill them.
#### Who?

Project Lead: Ben Golder @bengolder

Contributors:
- Gaurav @gauravmk
- Marlene @mfeil4
- Brennan @bhoeting, 
#### Why?

Many agencies and institutions that provide important services still rely on paper forms for intake. It is hard for them to adopt things like web forms unless they can integrate it with their existing paper process. This project hopes to make it easier for civic hackers to build web services that fill PDF forms. More details [here](https://github.com/codeforamerica/typeseam/pull/25) and [here](https://github.com/codeforamerica/pdfhook).
#### Needs
- Python programmers (particularly Flask)
- Beginners and non-programmers who want to help test and document project setup
- Someone who'd like to make a simple landing page that can be used for demo & documentation
### Current priorities
- **Make it easier to contribute**
  - Document setup and installation
  - Reduce dependencies
  - Add a basic working test suite
  - Add documentation, including an index page

**Comment by bengolder** [comment]
Today was extremely successful, and there a lot of new contributors.

The app is now easier to setup, to test, and fills PDFs out of the box!

@zhoux10 made a front page
![image](https://cloud.githubusercontent.com/assets/451510/13551443/11c992a6-e2ef-11e5-990c-90cd0c9a9226.png)

@gauravmk got the tests to start passing
![screen shot 2016-03-05 at 4 17 25 pm](https://cloud.githubusercontent.com/assets/451510/13551416/c866c5bc-e2ed-11e5-8f24-c57da51b880b.png)
- Danny Roa asked [a lot of great questions](https://github.com/codeforamerica/pdfhook/issues/16) that many might have about the project which were captured and can be used to improve the documentation and helped debug the setup process.
- @debrasol Debra, who worked at HSA, [wrote out some of the possible benefits and concerns](https://github.com/codeforamerica/pdfhook/issues/18) that agencies and institutions might have if someone were using this in the field and integrate it into their services.
- @bengolder Ben & @gauravmk Gaurav brainstormed [a big set of integration tests](https://github.com/codeforamerica/pdfhook/issues/26) that we hope the app will eventually pass.
- @joffemd Mark brought his expertise on pdf tools to the table and researched some [alternatives to the pdftk command line utility](https://github.com/codeforamerica/pdfhook/issues/20) this depends on and found a couple possible candidates: PDFBox & Poppler. He also looked at some commercial products to give some ideas for the demo page or other possible uses.
- @gauravmk Gaurav got the tests running, cleaned out obselete tests, and now we have an app that actually fills pdfs in the integration tests! He also made sure that it the app cleans up after itself, removing temporary files after requests are completed.
- @zhoux10 Sherry [created a front page](https://github.com/codeforamerica/pdfhook/pull/30) so that will soon allow you to upload pdfs as a demo when you get the app running out of the box
- @samgensburg Sam started [converting it to use sqlite](https://github.com/codeforamerica/pdfhook/pull/31), so that it's much easier to use out of the box and does not depend on postgresql. He also advised on ways that it can better capture errors from the command line utility
- @samgensburg and @zhoux10 both helped us check for pitfalls in the process of [installing Python 3](https://github.com/codeforamerica/pdfhook/commit/a0ead4e1e574cf1282700ca331293333181a50a7)
- @NoahKunin Noah stopped by and explained the potential value of this tool to the federal government.

**Comment by gauravmk** [comment]
![screen shot 2016-03-05 at 4 34 38 pm](https://cloud.githubusercontent.com/assets/16271389/13551480/3b6f1a4e-e2f0-11e5-80c8-e74bc6fa19fd.png)

![screen shot 2016-03-05 at 4 34 30 pm](https://cloud.githubusercontent.com/assets/16271389/13551479/3b6eda2a-e2f0-11e5-836b-857cc1b09a61.png)
