### ISSUE TITLE
Create Minimal Front End

### ISSUE THREAD

**Issue by marata29** [codeforamerica/pdfhook#8]
- [x] Create a basic HTML front page with a pdf file upload input
- [x] Get the front page to successfully submit PDFs
- [x] Distinguish between browsers and api calls [based on mimetypes](https://github.com/codeforamerica/pdfhook/issues/8#issuecomment-192781543)
- [x] list available pdf endpoints on front page
- [x] Create a json submission page that displays the expected schema

**Comment by bengolder** [comment]
<img src="https://cloud.githubusercontent.com/assets/451510/13485766/db44b1c4-e0bf-11e5-84fd-69c5fe630f96.png" width="250">

**Comment by cssherry** [comment]
Currently, has a main page, ideally, would show all the uploaded pdfs and allow users to submit json to them...

**Comment by bengolder** [comment]
Just a thought, but it would be nice to be able to differentiate between requests being loaded in a browser (which should render a browseable demo version of the functionality) and being loaded as an API (which should just return a JSON). I know that [Django REST Framework](http://www.django-rest-framework.org/) seems to do a great job of either serving JSONs or a browseable version of the API, depending on how you access the url.

How do they do this? Is there an easy way for us to mimic this functionality?

![image](https://cloud.githubusercontent.com/assets/451510/13551518/ac85e892-e2f1-11e5-8065-7dae51494754.png)

**Comment by bhoeting** [comment]
Here's the docs that flask has on that:  http://flask.pocoo.org/snippets/45/

**Comment by bengolder** [comment]
Thanks to @zhoux10, this is mostly implemented.

I'm expanding the scope of this issue to cover the behavior that we'd like to see:

For the root path, `/`:
- [ ] determine the

**Comment by bengolder** [comment]
Closed with #54
